
name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
        
    - name: Step 3 - Build with Maven
      run: mvn clean install

    - name: Step 4 - Run tests
      run: mvn test
      
    - name: Step 5 -List the current directory
      run: ls -a

    - name: Step 6 -what is in the target folder?
      run: |
        cd target 
        ls -a
      
